### PR TITLE
Run pytest-mpl in CI and upload results as artifact

### LINKED ISSUE #29: Add mpl-image-compare to CI
Now, the pytests are not run with the --mpl option. The problem is that the fonts in the plots seem to be slightly different from OS to OS, so we can run the tests with --mpl on one of the OS's.

### PR DESCRIPTION
**Pull request by YannickJadoul**
Reprisal of #56. Resolves #29.

The solution to get hold of the results on failure is to upload the folder as a GitHub Actions "artifact".
I will collect results and upload the fixed images, in a second commit.

- I've chosen Ubuntu 3.11 as the (current) latest version, as I would expect it to be the most accessible platform with the least amount of issues.
- I don't know how well other platforms would match? We could try to run the same tests on other platforms?
- Maybe we ought to pin matplotlib for these tests as well?

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Updated images in 1c0cf66 should still be checked to see if they are indeed correct!

**Comment by YannickJadoul** [comment]
I've tracked down part of the issue of why the one test is causing issues. Or at least, I found a workaround.
There seems to be something going on with the `classic` style if it's saved outside of the style context manager (as pytest-mpl does). Possibly some sort of conflict between different parameters between the `rcParams` read when creating the figure and when calling `savefig()`, as the figsize between `classic` and `default` also changes.

```python
import matplotlib.pyplot as plt

with plt.style.context('classic'):
    fig, ax = plt.subplots()
fig.savefig(f"test.png")
```

One solution seems to be to just change the default style to be set by pytest-mpl to `default`.
Another solution is to make sure we don't save a figure outside of the context manager.

Now that this works, we can see how other OSes like macOS and Windows will behave! A well-enough matching version of matplotlib and lilypond will still be necessary, anyway, but apart from that, maybe things will Just Work™ cross-platform!

**Comment by Jellevanderwerff** [comment]
Fantastic work Y! We're almost there. 

* I don't see a reason to implement saving the figures inside the context manager. This would mean implementing an ``fname`` parameter in all plotting functions, right?. I think getting people to use ``pyplot.figure.Figure.savefig()`` is better. The only situation we're not accounting for is that if people want to use the ``classic`` style  they'd have to explicitly set that in the same context as where they're saving. It's an ugly style anyway, so unless the same happens for other styles, I'm happy now.
* To get consistency in used lilypond versions during testing I suggest not using the (system-wide) binaries from the OS's respective package managers in the CI, but rather use the wheels from PyPI. The version now used on ``Ubuntu-latest``, installed using apt is almost two years old (v2.22.1), whereas the latest stable release is 2.24.3. The PyPI wheels instead are updated regularly. 

If agreed, we can rebase 00f17ef59dae6fbcbb4077c0b26b39bcaa32f66c to this branch, then re-generate the baseline images, then see if we get the same output across OS's.

**Comment by Jellevanderwerff** [comment]
Tested on branch ``use_pip_lilypond``. The generated lilypond images still differ between Mac OS and Ubuntu, even when using identical versions of matplotlib and lilypond (as is the case on that branch). RMS difference is now quite small though. Can I propose making another custom mpl decorator, specifically for use with lilypond, with a small tolerance (e.g. 3/4?).

**Comment by YannickJadoul** [comment]
> I suggest not using the (system-wide) binaries from the OS's respective package managers in the CI, but rather use the wheels from PyPI.

I hadn't thought so far ahead yet, but that does seem like a good idea, yes!
At any rate, we have mocked/monkeypatched tests for all sorts of different combinations of lilypond installs, and we're now _only_ using system lilypond. So yeah, switching should not have too much of an influence? Plus, it allows us to more easily duplicate the CI environment locally!

> Tested on branch `use_pip_lilypond`

Woohooo, thanks! I'm now trying here what the differences are without. But yes, I can take that commit, then, thanks :-)

**Comment by YannickJadoul** [comment]
> I don't see a reason to implement saving the figures inside the context manager. This would mean implementing an `fname` parameter in all plotting functions, right?. I think getting people to use `pyplot.figure.Figure.savefig()` is better.

No, agreed, I don't want to push any more parameters into that function! My suggestion would be to tear out the `style` parameter from the plotting functions, and make examples that do e.g. the following:

```python
with plt.style.context('ggplot', after_reset=True):
    fig, ax = plot_multiple_sequences(trials, style="classic", suppress_display=True)
    fig.savefig(f"test_{i}.png")
```

It teaches the right patterns, makes sure users don't get any surprises (like the one I debugged for a couple of hours), and allows to also styles that aren't set with a simple `plt.style.context(style)` (like `sns.axes_style`) and would resolve #44.

But that's a different and future discussion, and nothing for this PR.

> The only situation we're not accounting for is that if people want to use the `classic` style  they'd have to explicitly set that in the same context as where they're saving. It's an ugly style anyway, so unless the same happens for other styles, I'm happy now.

I don't know what other weird interactions between different styles would happen, though. So I'm not sure what other surprises to expect. But yes, agree that this is good enough for now, and for this PR!

**Comment by YannickJadoul** [comment]
> > Tested on branch `use_pip_lilypond`
> 
> Woohooo, thanks! I'm now trying here what the differences are without. But yes, I can take that commit, then, thanks :-)

Fun fact: we already install pip's `lilypond` as an optional dependency as  `[music_notation]` (which gets installed in CI). Moreover, we do test the that pip-installed version gets precedence over the system-wide install:
https://github.com/Jellevanderwerff/thebeat/blob/164530ed3dd1a361a839f0167ceba96a8bf164ac/tests/test_lilypond.py#L73-L80

On the `use_pip_lilypond` branch, some of these tests get skipped, since no system install is available!
https://github.com/Jellevanderwerff/thebeat/actions/runs/7336641500/job/19976266032#step:7:23

So, all together, we can just leave things like this, as we should have lilypond anyway.
We could still make this explicit, by installing lilypond separately (and potentially adding a comment), if you prefer? We could also pin lilypond for the tests, but not sure how important that is.

I'll still some custom exceptions to the zero-tolerance for tests with lilypond, now.

**Comment by YannickJadoul** [comment]
Almost ready, but there's one more weird thing going on. The sizes of the generated image are pretty weird.
E.g.:
- The lilypond images are now massive (3840x2880)
- `test_plot_multiple_sequences_0.png` did rescale to the `default` style's default size (800x600 -> 640x480), whereas some others didn't (`test_plot_stimulus_waveform_0.png` stayed 800*550)

@Jellevanderwerff, any idea why? Before merging this PR, it would be nice to know, such that we commit the right baseline for the future.
Also note that for the other images most changes seem to come from the difference in `classic`/`default`'s `plt.rcParams['axes.xmargin']`/`plt.rcParams['axes.ymargin']`.

Apart from that, I think I'm all done.
There's still the option of pinning matplotlib and/or lilypond, but I'd say we can try like this and see how often we get the annoyance of things changing in either.
There's also the issue of the style, but as said, let's keep for another PR/issue!

**Comment by Jellevanderwerff** [comment]
Yes, I think I know why. That's probably because we first generate the ``fig`` and ``ax``, then draw the (lilypond-generated) image file onto it, and then use a sort of ``NumPy`` hack to remove all white areas around the image. This is because lilypond for some reason generates images that contain white areas around it. I'll check if this issue can be resolved by rescaling the fig to its original size after removing the white areas.

**Comment by YannickJadoul** [comment]
Alright, makes sense, but still weird that this changed in ff3e08b2f58bfaa00d7d6c71d926d1e9417651d4, only after we changed the basic style, no?

**Comment by Jellevanderwerff** [comment]
Sorry I was mistaken: we don’t use that hack anymore, instead we now use the ‘’--dcrop’’ option in the lilypond subprocess call. I guess then it’s to do with us changing the figsize only, and matplotlib trying to keep the aspect ratio (which makes sense).

**Comment by YannickJadoul** [comment]
I figured out why the lilypond-related plots are suddenly massive. `Figure.savefig` takes the value from `plt.rcParams` if no argument for `dpi` is passed. For the `default` style, `savefig.dpi` is set to `'figure'` (i.e., take the value stored in the figure), but for `classic` it is still set to 100.

So the following three pieces of code react differently:

```python
with plt.style.context('classic'):
    fig, ax = plt.subplots(figsize=None, dpi=600)
    I = matplotlib.image.imread("lilypond.png")
    ax.imshow(I)
    ax.set_axis_off()
    fig.savefig("classic.png", dpi='figure')  # Saves with the 600 DPI from Figure
    
with plt.style.context('classic'):
    fig, ax = plt.subplots(figsize=None, dpi=600)
    I = matplotlib.image.imread("lilypond.png")
    ax.imshow(I)
    ax.set_axis_off()
    fig.savefig("classic.png")  # Saves with the default 100 DPI from classic's plt.rcParams
    
with plt.style.context('default'):
    fig, ax = plt.subplots(figsize=None, dpi=600)
    I = matplotlib.image.imread("lilypond.png")
    ax.imshow(I)
    ax.set_axis_off()
    fig.savefig("classic.png")  # Saves with the 600 DPI from Figure, since 'figure' is in default's plt.rcParams['savefig.dpi']
```

So I'm guessing this is fine for now, but:
- Another reason to look out with mixing styles inside and outside a context manager.
- I feel like the `dpi` argument is somewhat confusingly mixed between lilypond and matplotlib?
- What's the reason for putting the lilypond-generated figure inside another matploblib figure? (That's another issue/discussion, though; not relevant to this PR)

I should still check the other unexpected dimensions, but something similar is going on there: the `seaborn-v0_8` style's default figsize is `[8.0, 5.5]`. Since I assume we're not in a rush to merge this PR, I'll still give this a look over the next few days.

**Comment by YannickJadoul** [comment]
Alright, after a fresh look, all the new sizes of baseline figures seem to be explainable by the new combinations of pytest-mpl default style (`default` instead of `classic`), default sizes of other styles (`seaborn-v0_8` has `(8.0, 5.5)` as default `figsize`) , and custom sizes as default argument values in thebeat and tests.

I'll turn the remaining discussions (default styles and thebeat's handling of styles, and DPI/matplotlib for lilypond into two new issues for discussion).
But this PR can be merged if @Jellevanderwerff can have a final look at it and agrees with changes!

**Comment by Jellevanderwerff** [comment]
Perfect, thanks Y! Merged, and let's indneed discuss the other issues elsewhere :)

**Pull request merged**
